# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Askgpt < Formula
  desc ""
  homepage "https://github.com/sariserhat/homebrew-tools"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/serhhatsari/askgpt/releases/download/v1.3.0/askgpt_Darwin_x86_64.tar.gz"
      sha256 "c8d4103b5dd1584c9f0cbfa3753fada8159cd8bc88fe5f70973138a93516d833"

      def install
        bin.install "askgpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/serhhatsari/askgpt/releases/download/v1.3.0/askgpt_Darwin_arm64.tar.gz"
      sha256 "e327de59a7976f3b7c8394d8499efda1eb879c86d034fa48febd214bdab8575c"

      def install
        bin.install "askgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/serhhatsari/askgpt/releases/download/v1.3.0/askgpt_Linux_arm64.tar.gz"
      sha256 "267f4ea8fc05305903b4ae85ca84358c31ba8f7c50231db4fe5c712da6024bc1"

      def install
        bin.install "askgpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/serhhatsari/askgpt/releases/download/v1.3.0/askgpt_Linux_x86_64.tar.gz"
      sha256 "a1f8606a26394e9fdf313a4fdb3c2c88d3c3548f62a752ab19c06cb1f4dde591"

      def install
        bin.install "askgpt"
      end
    end
  end
end
