# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Askgpt < Formula
  desc ""
  homepage "https://github.com/sariserhat/homebrew-tools"
  version "1.2.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/serhhatsari/askgpt/releases/download/v1.2.4/askgpt_Darwin_arm64.tar.gz"
      sha256 "a7611ae50bd9e55fde9e458a482ae5185ef8c1116984b35d2164b510619ea922"

      def install
        bin.install "askgpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/serhhatsari/askgpt/releases/download/v1.2.4/askgpt_Darwin_x86_64.tar.gz"
      sha256 "0af42beb89d77e54f7b79d02aa0ccd69f42deccefe1397e993120d828b205e7b"

      def install
        bin.install "askgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/serhhatsari/askgpt/releases/download/v1.2.4/askgpt_Linux_arm64.tar.gz"
      sha256 "522d20b6eddf9ab7aa881854a0f975b692063ca6bcd4b7544d6adb22dbee050b"

      def install
        bin.install "askgpt"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/serhhatsari/askgpt/releases/download/v1.2.4/askgpt_Linux_x86_64.tar.gz"
      sha256 "01d1772180a858cdc2048ef47a254f85e6756f68c9b0a63b22c3200eb356695e"

      def install
        bin.install "askgpt"
      end
    end
  end
end
